# Generated by Django 6.0.6 on 2026-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_libro_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
    ]
