# Generated by Django 6.0.6 on 2026-06-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_libro_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='paginas',
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=100)),
                ('numero_edicion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_publicacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('autor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.autor')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='libros', to='biblioteca.tag'),
        ),
    ]
