# Generated by Django 6.0.6 on 2026-06-12 00:43

from django.db import migrations

GENEROS = [
    'Novela', 'Cuento', 'Poesía',
    'Ensayo', 'Teatro', 'Crónica',
    'Terror', 'Ciencia Ficción'
]
def poblar_generos(apps, schema_editor):
    Genero = apps.get_model('biblioteca', 'Genero')
    for nombre in GENEROS:
        Genero.objects.get_or_create(nombre=nombre)


def revertir_generos(apps, schema_editor):

    Genero = apps.get_model('biblioteca', 'Genero')

    Genero.objects.filter(nombre__in=GENEROS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_tag_remove_autor_biografia_and_more'),
    ]

    operations = [
            migrations.RunPython(poblar_generos, revertir_generos),
    ]


